version: '3'
services:
  eshopping:
    depends_on:
      - db
    build:
      context: .
    environment:
      DB_URL: 'jdbc:mysql://db:3306/spring_security_data?serverTimezone=UTC'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'Test@12345'
      ACTIVE_PROFILE: 'docker'
    ports:
      - 8082:8082
    networks:
      - eshopping
  db:
    image: mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'Test@12345'
      MYSQL_DATABASE: 'spring_security_data'
    ports:
      - 3306:3306
    networks:
      - eshopping
networks:
  eshopping:
    driver: bridge

